-- 영우 SQL START
CREATE TABLE member (
    memberId VARCHAR2(20),
    memberPw VARCHAR2(30) NOT NULL,
    memberName VARCHAR2(15) NOT NULL,
    memberAddress VARCHAR2(100) NOT NULL,
    memberPhone VARCHAR2(20) NOT NULL,
    memberBirth DATE NOT NULL,
    memberEmail VARCHAR2(100) NOT NULL
);

CREATE TABLE auth(
    memberId VARCHAR2(20) NOT NULL,
    memberAuth VARCHAR2(20) NOT NULL
);

CREATE TABLE suggest(
    suggestNo NUMBER(10),
    memberID VARCHAR2(20) NOT NULL,
    suggestTitle VARCHAR2(100) NOT NULL,
    suggestContent VARCHAR2(1000) NOT NULL,
    suggestPrivateChk NUMBER(1) DEFAULT 0 NOT NULL,
    suggestPw VARCHAR2(30),
    suggestView NUMBER(10) DEFAULT 0 NOT NULL
);

-- 영우 알터 START
ALTER TABLE member ADD CONSTRAINT pk_memberId PRIMARY KEY(memberId);
ALTER TABLE auth ADD CONSTRAINT fk_auth_memberId FOREIGN KEY (memberId) REFERENCES member(memberId) ON DELETE CASCADE;
ALTER TABLE suggest ADD CONSTRAINT fk_suggest_memberId foreign key (memberId) REFERENCES member(memberId) ON DELETE CASCADE;
-- 영우 알터 END
-- 영우 SQL END

-- 한나 SQL START
CREATE TABLE RESERVE (
    reserveNo VARCHAR2(20) NOT NULL,
    memberId VARCHAR2(20) NOT NULL,
    seat VARCHAR2(20) NOT NULL,
    scheduleNo NUMBER(10) NOT NULL,
    adultNum NUMBER(10) DEFAULT 0,
    teenNum NUMBER(10) DEFAULT 0,
    status NUMBER(10) DEFAULT 0
);

CREATE TABLE SCHEDULE (
    scheduleNo NUMBER(10) NOT NULL,
    scheduleDate DATE NOT NULL,
    scheduleTime VARCHAR2(20) NOT NULL,
    screen VARCHAR2(20) NOT NULL,
    movieNo NUMBER(10) NOT NULL
);

CREATE TABLE SEAT (
    scheduleNo NUMBER(10) NOT NULL,
    seatNo VARCHAR2(20) NOT NULL,
    seatStatus NUMBER(10) DEFAULT 0
);
-- 한나 ALTER START
ALTER TABLE RESERVE ADD CONSTRAINT RESERVE_PK PRIMARY KEY (reserveNo);
ALTER TABLE RESERVE ADD CONSTRAINT RESERVE_FK1 FOREIGN KEY (memberId) REFERENCES MEMBER(memberId) ON DELETE CASCADE;
ALTER TABLE RESERVE ADD CONSTRAINT RESERVE_FK2 FOREIGN KEY (scheduleNo) REFERENCES SCHEDULE(scheduleNo) ON DELETE CASCADE;

ALTER TABLE SCHEDULE ADD CONSTRAINT SCHEDULE_PK PRIMARY KEY (scheduleNo);
ALTER TABLE SCHEDULE ADD CONSTRAINT SCHEDULE_FK FOREIGN KEY (movieNo) REFERENCES MOVIE(movieNo) ON DELETE CASCADE;

ALTER TABLE SEAT ADD CONSTRAINT SEAT_PK PRIMARY KEY (scheduleNo, seatNo);
ALTER TABLE SEAT ADD CONSTRAINT SEAT_FK FOREIGN KEY (scheduleNo) REFERENCES SCHEDULE(scheduleNo) ON DELETE CASCADE;

CREATE SEQUENCE seq_schedule;
-- 한나 ALTER END
-- 한나 SQL END

CREATE TABLE notice (
 noticeNo NUMBER(10),
 noticeTitle VARCHAR2(100) NOT NULL,
 noticeContent VARCHAR2(1000) NOT NULL,
 noticeView NUMBER(10) DEFAULT 0,
 noticeDate DATE DEFAULT SYSDATE
);

-- 진주 SQL START
CREATE TABLE gift(
    giftNo NUMBER(10),
    giftName VARCHAR2(100) NOT NULL,
    giftPrice NUMBER(10) NOT NULL,
    giftSet VARCHAR2(200) NOT NULL
);

CREATE TABLE myGift(
    memberId VARCHAR2(20) NOT NULL,
    giftNo NUMBER(10) NOT NULL,
    myGiftNo NUMBER(10),
    status NUMBER(10) NOT NULL,
    buyingDate DATE DEFAULT SYSDATE,
    expireDate DATE DEFAULT SYSDATE + (INTERVAL '1' MONTH),
    extendChk CHAR(1) NOT NULL
);

CREATE TABLE giftAttach(
    giftUuid VARCHAR2(100),
    giftUploadPath VARCHAR2(200) NOT NULL,
    giftFileName VARCHAR2(100) NOT NULL,
    giftNo NUMBER(10) NOT NULL
);

-- 진주 알터 START
ALTER TABLE notice ADD CONSTRAINT NOTICE_PK PRIMARY KEY(noticeNo);
ALTER TABLE gift ADD CONSTRAINT GIFT_PK PRIMARY KEY(giftNo);
ALTER TABLE myGift ADD CONSTRAINT MYGIFT_PK PRIMARY KEY(myGiftNo);
ALTER TABLE myGift ADD CONSTRAINT MYGIFT_FK1 FOREIGN KEY (giftNo) REFERENCES gift (giftNo);
ALTER TABLE myGift ADD CONSTRAINT MYGIFT_FK2 FOREIGN KEY (memberId) REFERENCES member (memberId) ON DELETE SET NULL;
ALTER TABLE giftAttach ADD CONSTRAINT GIFTATTACH_PK PRIMARY KEY(giftUuid);
ALTER TABLE giftAttach ADD CONSTRAINT GIFTATTACH_FK FOREIGN KEY(giftNo) REFERENCES gift (giftNo) ON DELETE CASCADE;
-- 진주 알터 END
-- 진주 SQL END

--DROP TABLE MEMBER;
--DROP TABLE AUTH;
--DROP TABLE GIFT;
--DROP TABLE GIFTATTACH;
--DROP TABLE MYGIFT;
--DROP TABLE NOTICE;
--DROP TABLE RESERVE;
--DROP TABLE SCHEDULE;
--DROP TABLE SEAT;
--DROP TABLE SUGGEST;

